### ISSUE TITLE
Spot Client submitNewOrder() and testNewOrder() broken in 2.0.19+

### ISSUE THREAD

**Issue by d11wtq** [tiagosiebler/binance#179]
We were chatting earlier directly on a commit message. I upgraded from 2.0.12 to 2.0.19 (and then 2.0.20) today, in an attempt to fix an issue around reconnecting to the spot UserData stream after a connection outage. I have a completely new issue now however. I'm getting the following whenever a new order is submitted:

```
{
  code: -1102,
  message: "Mandatory parameter 'symbol' was not sent, was empty/null, or malformed.",
```

This also happens with `testNewOrder` too. See below. It appears there's some double-encoding happening here?

I'm passing the exact same parameters as I was passing in 2.0.12, which was working nicely aside from the reconnect issue.

```
https://api.binance.com/api/v3/order/test?symbol%3DMIRUSDT%26side%3DBUY%26type%3DLIMIT%26newClientOrderId%3DREADACTED%26price%3D2.56800000%26quantity%3D62.30000000%26timeInForce%3DGTC%26newOrderRespType%3DFULL%26timestamp%3D1639114165191%26recvWindow%3D5000&timestamp=1639114165191&recvWindow=5000&signature=REDACTED
```

You can see here all the `=` and `&` syntax has been URL-encoded to `%3D` and `%26`, which completely breaks the request syntax.

**Comment by d11wtq** [comment]
Almost certainly this is wrong?

```
options.url += '?' + [encodeURIComponent(signed.serialisedParams),
```

That's encoding the entire params as a single URL-component, hence the issue. This means _all_ "private" REST client endpoints that are not GET or DELETE will be broken I think.

**Comment by d11wtq** [comment]
Removed that `encodeURIComponent()` because AFAICT it's already encoded in the `signed` object, but then I get a `Duplicate values for parameter 'timestamp'.`, which is true because that's also in the signed object too. I'll need to downgrade back to 2.0.12 I think as this feels a little too broken to feel confident fiddling with 🙏 

I'll try and look closer at this later. I'm surprised nobody else has run into this at all. Are most people not using the spot client?

**Comment by tiagosiebler** [comment]
I'm also surprised nobody raised this...I'm dominantly in futures at the moment, but I'll also take a look as soon as I can. Your findings are very helpful in narrowing the scope - thank you for the time spent on this so far.

**Comment by tiagosiebler** [comment]
> Almost certainly this is wrong?
> 
> ```
> options.url += '?' + [encodeURIComponent(signed.serialisedParams),
> ```
> 
> That's encoding the entire params as a single URL-component, hence the issue. This means _all_ "private" REST client endpoints that are not GET or DELETE will be broken I think.

Looks like you were absolutely right (I was troubleshooting another issue with this already). It's only the values that should be encoded. Everything else should be in tact. I'll open a PR and push a beta version soon, could you help test it too? I have a system I can test with thoroughly on futures, but spot is a bit more manual for me to test.

**Comment by tiagosiebler** [comment]
@d11wtq Hi Chris, I've pushed a fix as a beta release - you can see it in #180 if you're curious. I'd appreciate if you could try it out and let me know if all endpoints you're interested in are now working for you: `npm install binance@beta`
Thanks!

**Comment by tiagosiebler** [comment]
@d11wtq following testing in #180 and confirmation in spot & futures, I've pushed it to stable release under v2.0.20. Would love to hear when you have a chance to test.

**Comment by d11wtq** [comment]
Hi @tiagosiebler so sorry for the delay in responding. Been a hectic weekend.

Installing 2.0.20 the error is still present.

> Mandatory parameter 'symbol' was not sent, was empty/null, or malformed.

```
https://testnet.binance.vision/api/v3/order?symbol%3DBTCUSDT%26side%3DBUY%26type%3DLIMIT%26newClientOrderId%3Dx-U5D79M5BgC3PRHAtpxwHALk%26price%3D49010.00000000%26quantity%3D0.69470700%26timeInForce%3DGTC%26newOrderRespType%3DFULL%26timestamp%3D1639289425483%26recvWindow%3D5000&timestamp=1639289425483&recvWindow=5000&signature=REDACTED
```

But in 2.0.21, everything is working as expected, thank you ❤️

**Comment by tiagosiebler** [comment]
Nice, thanks for confirming. Glad to hear it.
